title: QIU1995NONAME 's Documents
email: qmh1995@163.com 
description: Documents of QIU1995NONAME
github_username: QIU1995NONAME
url: https://qiu1995noname.github.io
baseurl: /QBlogs
markdown: kramdown
theme: jekyll-theme-hacker

show_downloads: true
show_subscribe: true
enable_mathjax: true
enable_mermaid: true

mermaid_version: '7.1.0'

